package com.unbosque.entidad;
// default package
// Generated Apr 26, 2015 6:24:07 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name = "ciudad", schema = "public")
public class Ciudad implements java.io.Serializable {

	private int id;
	private String nombre;
	private Character estado;
	private String depto;

	public Ciudad() {
	}

	public Ciudad(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Ciudad(int id, String nombre, Character estado, String depto) {
		this.id = id;
		this.nombre = nombre;
		this.estado = estado;
		this.depto = depto;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "depto", length = 80)
	public String getDepto() {
		return this.depto;
	}

	public void setDepto(String depto) {
		this.depto = depto;
	}

}
