package com.unbosque.entidad;
// default package
// Generated Apr 25, 2015 6:20:05 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento", schema = "public")
public class Departamento implements java.io.Serializable {

	private int id;
	private String nombre;
	private char estado;

	public Departamento() {
	}

	public Departamento(int id, String nombre, char estado) {
		this.id = id;
		this.nombre = nombre;
		this.estado = estado;
	}
	public Departamento(String nombre, char estado) {
		this.nombre = nombre;
		this.estado = estado;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

}
