package com.unbosque.entidad;

// Generated May 1, 2015 9:14:54 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Diente generated by hbm2java
 */
@Entity
@Table(name = "diente", schema = "public")
public class Diente implements java.io.Serializable {

	
	
	private int id;
	
	private Integer darriba1;
	private Integer dabajo1;
	private Integer dcentro1;
	private Integer dizquierda1;
	private Integer dderecha1;

	public Diente() {
	}

	public Diente(int id) {
		this.id = id;
	}

	public Diente(int id, Integer darriba1, Integer dabajo1, Integer dcentro1,
			Integer dizquierda1, Integer dderecha1) {
		this.id = id;
		this.darriba1 = darriba1;
		this.dabajo1 = dabajo1;
		this.dcentro1 = dcentro1;
		this.dizquierda1 = dizquierda1;
		this.dderecha1 = dderecha1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Darriba1")
	public Integer getDarriba1() {
		return this.darriba1;
	}

	public void setDarriba1(Integer darriba1) {
		this.darriba1 = darriba1;
	}

	@Column(name = "Dabajo1")
	public Integer getDabajo1() {
		return this.dabajo1;
	}

	public void setDabajo1(Integer dabajo1) {
		this.dabajo1 = dabajo1;
	}

	@Column(name = "Dcentro1")
	public Integer getDcentro1() {
		return this.dcentro1;
	}

	public void setDcentro1(Integer dcentro1) {
		this.dcentro1 = dcentro1;
	}

	@Column(name = "Dizquierda1")
	public Integer getDizquierda1() {
		return this.dizquierda1;
	}

	public void setDizquierda1(Integer dizquierda1) {
		this.dizquierda1 = dizquierda1;
	}

	@Column(name = "Dderecha1")
	public Integer getDderecha1() {
		return this.dderecha1;
	}

	public void setDderecha1(Integer dderecha1) {
		this.dderecha1 = dderecha1;
	}

}
