package com.unbosque.entidad;
// default package
// Generated May 3, 2015 6:48:35 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Donto generated by hbm2java
 */
@Entity
@Table(name = "donto", schema = "public")
public class Donto implements java.io.Serializable {

	private int id;
	private Integer identificacion;
	private Integer cd11;
	private Integer cd12;
	private Integer cd13;
	private Integer cd14;
	private Integer cd15;
	private String d1coment;
	private Integer cd21;
	private Integer cd22;
	private Integer cd23;
	private Integer cd24;
	private Integer cd25;
	private String d2coment;
	private Integer cd31;
	private Integer cd32;
	private Integer cd33;
	private Integer cd34;
	private Integer cd35;
	private String d3coment;
	private Integer cd41;
	private Integer cd42;
	private Integer cd43;
	private Integer cd44;
	private Integer cd45;
	private String d4coment;
	private Integer cd51;
	private Integer cd52;
	private Integer cd53;
	private Integer cd54;
	private Integer cd55;
	private String d5coment;
	private Integer cd61;
	private Integer cd62;
	private Integer cd63;
	private Integer cd64;
	private Integer cd65;
	private String d6coment;
	private Integer cd71;
	private Integer cd72;
	private Integer cd73;
	private Integer cd74;
	private Integer cd75;
	private String d7coment;
	private Integer cd81;
	private Integer cd82;
	private Integer cd83;
	private Integer cd84;
	private Integer cd85;
	private String d8coment;
	private Integer cd91;
	private Integer cd92;
	private Integer cd93;
	private Integer cd94;
	private Integer cd95;
	private String d9coment;
	private Integer cd101;
	private Integer cd102;
	private Integer cd103;
	private Integer cd104;
	private Integer cd105;
	private String d10coment;
	private Integer cd111;
	private Integer cd112;
	private Integer cd113;
	private Integer cd114;
	private Integer cd115;
	private String d11coment;
	private Integer cd121;
	private Integer cd122;
	private Integer cd123;
	private Integer cd124;
	private Integer cd125;
	private String d12coment;
	private Integer cd131;
	private Integer cd132;
	private Integer cd133;
	private Integer cd134;
	private Integer cd135;
	private String d13coment;
	private Integer cd141;
	private Integer cd142;
	private Integer cd143;
	private Integer cd144;
	private Integer cd145;
	private String d14coment;
	private Integer cd151;
	private Integer cd152;
	private Integer cd153;
	private Integer cd154;
	private Integer cd155;
	private String d15coment;
	private Integer cd161;
	private Integer cd162;
	private Integer cd163;
	private Integer cd164;
	private Integer cd165;
	private String d16coment;
	private Integer cd171;
	private Integer cd172;
	private Integer cd173;
	private Integer cd174;
	private Integer cd175;
	private String d17coment;
	private Integer cd181;
	private Integer cd182;
	private Integer cd183;
	private Integer cd184;
	private Integer cd185;
	private String d18coment;
	private Integer cd191;
	private Integer cd192;
	private Integer cd193;
	private Integer cd194;
	private Integer cd195;
	private String d19coment;
	private Integer cd201;
	private Integer cd202;
	private Integer cd203;
	private Integer cd204;
	private Integer cd205;
	private String d20coment;
	private Integer cd211;
	private Integer cd212;
	private Integer cd213;
	private Integer cd214;
	private Integer cd215;
	private String d21coment;
	private Integer cd221;
	private Integer cd222;
	private Integer cd223;
	private Integer cd224;
	private Integer cd225;
	private String d22coment;
	private Integer cd231;
	private Integer cd232;
	private Integer cd233;
	private Integer cd234;
	private Integer cd235;
	private String d23coment;
	private Integer cd241;
	private Integer cd242;
	private Integer cd243;
	private Integer cd244;
	private Integer cd245;
	private String d24coment;
	private Integer cd251;
	private Integer cd252;
	private Integer cd253;
	private Integer cd254;
	private Integer cd255;
	private String d25coment;
	private Integer cd261;
	private Integer cd262;
	private Integer cd263;
	private Integer cd264;
	private Integer cd265;
	private String d26coment;
	private Integer cd271;
	private Integer cd272;
	private Integer cd273;
	private Integer cd274;
	private Integer cd275;
	private String d27coment;
	private Integer cd281;
	private Integer cd282;
	private Integer cd283;
	private Integer cd284;
	private Integer cd285;
	private String d28coment;
	private Integer cd291;
	private Integer cd292;
	private Integer cd293;
	private Integer cd294;
	private Integer cd295;
	private String d29coment;
	private Integer cd301;
	private Integer cd302;
	private Integer cd303;
	private Integer cd304;
	private Integer cd305;
	private String d30coment;
	private Integer cd311;
	private Integer cd312;
	private Integer cd313;
	private Integer cd314;
	private Integer cd315;
	private String d31coment;
	private Integer cd321;
	private Integer cd322;
	private Integer cd323;
	private Integer cd324;
	private Integer cd325;
	private String d32coment;

	public Donto() {
	}

	public Donto(int id) {
		this.id = id;
	}

	public Donto(int id, Integer identificacion, Integer cd11, Integer cd12,
			Integer cd13, Integer cd14, Integer cd15, String d1coment,
			Integer cd21, Integer cd22, Integer cd23, Integer cd24,
			Integer cd25, String d2coment, Integer cd31, Integer cd32,
			Integer cd33, Integer cd34, Integer cd35, String d3coment,
			Integer cd41, Integer cd42, Integer cd43, Integer cd44,
			Integer cd45, String d4coment, Integer cd51, Integer cd52,
			Integer cd53, Integer cd54, Integer cd55, String d5coment,
			Integer cd61, Integer cd62, Integer cd63, Integer cd64,
			Integer cd65, String d6coment, Integer cd71, Integer cd72,
			Integer cd73, Integer cd74, Integer cd75, String d7coment,
			Integer cd81, Integer cd82, Integer cd83, Integer cd84,
			Integer cd85, String d8coment, Integer cd91, Integer cd92,
			Integer cd93, Integer cd94, Integer cd95, String d9coment,
			Integer cd101, Integer cd102, Integer cd103, Integer cd104,
			Integer cd105, String d10coment, Integer cd111, Integer cd112,
			Integer cd113, Integer cd114, Integer cd115, String d11coment,
			Integer cd121, Integer cd122, Integer cd123, Integer cd124,
			Integer cd125, String d12coment, Integer cd131, Integer cd132,
			Integer cd133, Integer cd134, Integer cd135, String d13coment,
			Integer cd141, Integer cd142, Integer cd143, Integer cd144,
			Integer cd145, String d14coment, Integer cd151, Integer cd152,
			Integer cd153, Integer cd154, Integer cd155, String d15coment,
			Integer cd161, Integer cd162, Integer cd163, Integer cd164,
			Integer cd165, String d16coment, Integer cd171, Integer cd172,
			Integer cd173, Integer cd174, Integer cd175, String d17coment,
			Integer cd181, Integer cd182, Integer cd183, Integer cd184,
			Integer cd185, String d18coment, Integer cd191, Integer cd192,
			Integer cd193, Integer cd194, Integer cd195, String d19coment,
			Integer cd201, Integer cd202, Integer cd203, Integer cd204,
			Integer cd205, String d20coment, Integer cd211, Integer cd212,
			Integer cd213, Integer cd214, Integer cd215, String d21coment,
			Integer cd221, Integer cd222, Integer cd223, Integer cd224,
			Integer cd225, String d22coment, Integer cd231, Integer cd232,
			Integer cd233, Integer cd234, Integer cd235, String d23coment,
			Integer cd241, Integer cd242, Integer cd243, Integer cd244,
			Integer cd245, String d24coment, Integer cd251, Integer cd252,
			Integer cd253, Integer cd254, Integer cd255, String d25coment,
			Integer cd261, Integer cd262, Integer cd263, Integer cd264,
			Integer cd265, String d26coment, Integer cd271, Integer cd272,
			Integer cd273, Integer cd274, Integer cd275, String d27coment,
			Integer cd281, Integer cd282, Integer cd283, Integer cd284,
			Integer cd285, String d28coment, Integer cd291, Integer cd292,
			Integer cd293, Integer cd294, Integer cd295, String d29coment,
			Integer cd301, Integer cd302, Integer cd303, Integer cd304,
			Integer cd305, String d30coment, Integer cd311, Integer cd312,
			Integer cd313, Integer cd314, Integer cd315, String d31coment,
			Integer cd321, Integer cd322, Integer cd323, Integer cd324,
			Integer cd325, String d32coment) {
		this.id = id;
		this.identificacion = identificacion;
		this.cd11 = cd11;
		this.cd12 = cd12;
		this.cd13 = cd13;
		this.cd14 = cd14;
		this.cd15 = cd15;
		this.d1coment = d1coment;
		this.cd21 = cd21;
		this.cd22 = cd22;
		this.cd23 = cd23;
		this.cd24 = cd24;
		this.cd25 = cd25;
		this.d2coment = d2coment;
		this.cd31 = cd31;
		this.cd32 = cd32;
		this.cd33 = cd33;
		this.cd34 = cd34;
		this.cd35 = cd35;
		this.d3coment = d3coment;
		this.cd41 = cd41;
		this.cd42 = cd42;
		this.cd43 = cd43;
		this.cd44 = cd44;
		this.cd45 = cd45;
		this.d4coment = d4coment;
		this.cd51 = cd51;
		this.cd52 = cd52;
		this.cd53 = cd53;
		this.cd54 = cd54;
		this.cd55 = cd55;
		this.d5coment = d5coment;
		this.cd61 = cd61;
		this.cd62 = cd62;
		this.cd63 = cd63;
		this.cd64 = cd64;
		this.cd65 = cd65;
		this.d6coment = d6coment;
		this.cd71 = cd71;
		this.cd72 = cd72;
		this.cd73 = cd73;
		this.cd74 = cd74;
		this.cd75 = cd75;
		this.d7coment = d7coment;
		this.cd81 = cd81;
		this.cd82 = cd82;
		this.cd83 = cd83;
		this.cd84 = cd84;
		this.cd85 = cd85;
		this.d8coment = d8coment;
		this.cd91 = cd91;
		this.cd92 = cd92;
		this.cd93 = cd93;
		this.cd94 = cd94;
		this.cd95 = cd95;
		this.d9coment = d9coment;
		this.cd101 = cd101;
		this.cd102 = cd102;
		this.cd103 = cd103;
		this.cd104 = cd104;
		this.cd105 = cd105;
		this.d10coment = d10coment;
		this.cd111 = cd111;
		this.cd112 = cd112;
		this.cd113 = cd113;
		this.cd114 = cd114;
		this.cd115 = cd115;
		this.d11coment = d11coment;
		this.cd121 = cd121;
		this.cd122 = cd122;
		this.cd123 = cd123;
		this.cd124 = cd124;
		this.cd125 = cd125;
		this.d12coment = d12coment;
		this.cd131 = cd131;
		this.cd132 = cd132;
		this.cd133 = cd133;
		this.cd134 = cd134;
		this.cd135 = cd135;
		this.d13coment = d13coment;
		this.cd141 = cd141;
		this.cd142 = cd142;
		this.cd143 = cd143;
		this.cd144 = cd144;
		this.cd145 = cd145;
		this.d14coment = d14coment;
		this.cd151 = cd151;
		this.cd152 = cd152;
		this.cd153 = cd153;
		this.cd154 = cd154;
		this.cd155 = cd155;
		this.d15coment = d15coment;
		this.cd161 = cd161;
		this.cd162 = cd162;
		this.cd163 = cd163;
		this.cd164 = cd164;
		this.cd165 = cd165;
		this.d16coment = d16coment;
		this.cd171 = cd171;
		this.cd172 = cd172;
		this.cd173 = cd173;
		this.cd174 = cd174;
		this.cd175 = cd175;
		this.d17coment = d17coment;
		this.cd181 = cd181;
		this.cd182 = cd182;
		this.cd183 = cd183;
		this.cd184 = cd184;
		this.cd185 = cd185;
		this.d18coment = d18coment;
		this.cd191 = cd191;
		this.cd192 = cd192;
		this.cd193 = cd193;
		this.cd194 = cd194;
		this.cd195 = cd195;
		this.d19coment = d19coment;
		this.cd201 = cd201;
		this.cd202 = cd202;
		this.cd203 = cd203;
		this.cd204 = cd204;
		this.cd205 = cd205;
		this.d20coment = d20coment;
		this.cd211 = cd211;
		this.cd212 = cd212;
		this.cd213 = cd213;
		this.cd214 = cd214;
		this.cd215 = cd215;
		this.d21coment = d21coment;
		this.cd221 = cd221;
		this.cd222 = cd222;
		this.cd223 = cd223;
		this.cd224 = cd224;
		this.cd225 = cd225;
		this.d22coment = d22coment;
		this.cd231 = cd231;
		this.cd232 = cd232;
		this.cd233 = cd233;
		this.cd234 = cd234;
		this.cd235 = cd235;
		this.d23coment = d23coment;
		this.cd241 = cd241;
		this.cd242 = cd242;
		this.cd243 = cd243;
		this.cd244 = cd244;
		this.cd245 = cd245;
		this.d24coment = d24coment;
		this.cd251 = cd251;
		this.cd252 = cd252;
		this.cd253 = cd253;
		this.cd254 = cd254;
		this.cd255 = cd255;
		this.d25coment = d25coment;
		this.cd261 = cd261;
		this.cd262 = cd262;
		this.cd263 = cd263;
		this.cd264 = cd264;
		this.cd265 = cd265;
		this.d26coment = d26coment;
		this.cd271 = cd271;
		this.cd272 = cd272;
		this.cd273 = cd273;
		this.cd274 = cd274;
		this.cd275 = cd275;
		this.d27coment = d27coment;
		this.cd281 = cd281;
		this.cd282 = cd282;
		this.cd283 = cd283;
		this.cd284 = cd284;
		this.cd285 = cd285;
		this.d28coment = d28coment;
		this.cd291 = cd291;
		this.cd292 = cd292;
		this.cd293 = cd293;
		this.cd294 = cd294;
		this.cd295 = cd295;
		this.d29coment = d29coment;
		this.cd301 = cd301;
		this.cd302 = cd302;
		this.cd303 = cd303;
		this.cd304 = cd304;
		this.cd305 = cd305;
		this.d30coment = d30coment;
		this.cd311 = cd311;
		this.cd312 = cd312;
		this.cd313 = cd313;
		this.cd314 = cd314;
		this.cd315 = cd315;
		this.d31coment = d31coment;
		this.cd321 = cd321;
		this.cd322 = cd322;
		this.cd323 = cd323;
		this.cd324 = cd324;
		this.cd325 = cd325;
		this.d32coment = d32coment;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "identificacion")
	public Integer getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(Integer identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "cd11")
	public Integer getCd11() {
		return this.cd11;
	}

	public void setCd11(Integer cd11) {
		this.cd11 = cd11;
	}

	@Column(name = "cd12")
	public Integer getCd12() {
		return this.cd12;
	}

	public void setCd12(Integer cd12) {
		this.cd12 = cd12;
	}

	@Column(name = "cd13")
	public Integer getCd13() {
		return this.cd13;
	}

	public void setCd13(Integer cd13) {
		this.cd13 = cd13;
	}

	@Column(name = "cd14")
	public Integer getCd14() {
		return this.cd14;
	}

	public void setCd14(Integer cd14) {
		this.cd14 = cd14;
	}

	@Column(name = "cd15")
	public Integer getCd15() {
		return this.cd15;
	}

	public void setCd15(Integer cd15) {
		this.cd15 = cd15;
	}

	@Column(name = "d1coment", length = 300)
	public String getD1coment() {
		return this.d1coment;
	}

	public void setD1coment(String d1coment) {
		this.d1coment = d1coment;
	}

	@Column(name = "cd21")
	public Integer getCd21() {
		return this.cd21;
	}

	public void setCd21(Integer cd21) {
		this.cd21 = cd21;
	}

	@Column(name = "cd22")
	public Integer getCd22() {
		return this.cd22;
	}

	public void setCd22(Integer cd22) {
		this.cd22 = cd22;
	}

	@Column(name = "cd23")
	public Integer getCd23() {
		return this.cd23;
	}

	public void setCd23(Integer cd23) {
		this.cd23 = cd23;
	}

	@Column(name = "cd24")
	public Integer getCd24() {
		return this.cd24;
	}

	public void setCd24(Integer cd24) {
		this.cd24 = cd24;
	}

	@Column(name = "cd25")
	public Integer getCd25() {
		return this.cd25;
	}

	public void setCd25(Integer cd25) {
		this.cd25 = cd25;
	}

	@Column(name = "d2coment", length = 300)
	public String getD2coment() {
		return this.d2coment;
	}

	public void setD2coment(String d2coment) {
		this.d2coment = d2coment;
	}

	@Column(name = "cd31")
	public Integer getCd31() {
		return this.cd31;
	}

	public void setCd31(Integer cd31) {
		this.cd31 = cd31;
	}

	@Column(name = "cd32")
	public Integer getCd32() {
		return this.cd32;
	}

	public void setCd32(Integer cd32) {
		this.cd32 = cd32;
	}

	@Column(name = "cd33")
	public Integer getCd33() {
		return this.cd33;
	}

	public void setCd33(Integer cd33) {
		this.cd33 = cd33;
	}

	@Column(name = "cd34")
	public Integer getCd34() {
		return this.cd34;
	}

	public void setCd34(Integer cd34) {
		this.cd34 = cd34;
	}

	@Column(name = "cd35")
	public Integer getCd35() {
		return this.cd35;
	}

	public void setCd35(Integer cd35) {
		this.cd35 = cd35;
	}

	@Column(name = "d3coment", length = 300)
	public String getD3coment() {
		return this.d3coment;
	}

	public void setD3coment(String d3coment) {
		this.d3coment = d3coment;
	}

	@Column(name = "cd41")
	public Integer getCd41() {
		return this.cd41;
	}

	public void setCd41(Integer cd41) {
		this.cd41 = cd41;
	}

	@Column(name = "cd42")
	public Integer getCd42() {
		return this.cd42;
	}

	public void setCd42(Integer cd42) {
		this.cd42 = cd42;
	}

	@Column(name = "cd43")
	public Integer getCd43() {
		return this.cd43;
	}

	public void setCd43(Integer cd43) {
		this.cd43 = cd43;
	}

	@Column(name = "cd44")
	public Integer getCd44() {
		return this.cd44;
	}

	public void setCd44(Integer cd44) {
		this.cd44 = cd44;
	}

	@Column(name = "cd45")
	public Integer getCd45() {
		return this.cd45;
	}

	public void setCd45(Integer cd45) {
		this.cd45 = cd45;
	}

	@Column(name = "d4coment", length = 300)
	public String getD4coment() {
		return this.d4coment;
	}

	public void setD4coment(String d4coment) {
		this.d4coment = d4coment;
	}

	@Column(name = "cd51")
	public Integer getCd51() {
		return this.cd51;
	}

	public void setCd51(Integer cd51) {
		this.cd51 = cd51;
	}

	@Column(name = "cd52")
	public Integer getCd52() {
		return this.cd52;
	}

	public void setCd52(Integer cd52) {
		this.cd52 = cd52;
	}

	@Column(name = "cd53")
	public Integer getCd53() {
		return this.cd53;
	}

	public void setCd53(Integer cd53) {
		this.cd53 = cd53;
	}

	@Column(name = "cd54")
	public Integer getCd54() {
		return this.cd54;
	}

	public void setCd54(Integer cd54) {
		this.cd54 = cd54;
	}

	@Column(name = "cd55")
	public Integer getCd55() {
		return this.cd55;
	}

	public void setCd55(Integer cd55) {
		this.cd55 = cd55;
	}

	@Column(name = "d5coment", length = 300)
	public String getD5coment() {
		return this.d5coment;
	}

	public void setD5coment(String d5coment) {
		this.d5coment = d5coment;
	}

	@Column(name = "cd61")
	public Integer getCd61() {
		return this.cd61;
	}

	public void setCd61(Integer cd61) {
		this.cd61 = cd61;
	}

	@Column(name = "cd62")
	public Integer getCd62() {
		return this.cd62;
	}

	public void setCd62(Integer cd62) {
		this.cd62 = cd62;
	}

	@Column(name = "cd63")
	public Integer getCd63() {
		return this.cd63;
	}

	public void setCd63(Integer cd63) {
		this.cd63 = cd63;
	}

	@Column(name = "cd64")
	public Integer getCd64() {
		return this.cd64;
	}

	public void setCd64(Integer cd64) {
		this.cd64 = cd64;
	}

	@Column(name = "cd65")
	public Integer getCd65() {
		return this.cd65;
	}

	public void setCd65(Integer cd65) {
		this.cd65 = cd65;
	}

	@Column(name = "d6coment", length = 300)
	public String getD6coment() {
		return this.d6coment;
	}

	public void setD6coment(String d6coment) {
		this.d6coment = d6coment;
	}

	@Column(name = "cd71")
	public Integer getCd71() {
		return this.cd71;
	}

	public void setCd71(Integer cd71) {
		this.cd71 = cd71;
	}

	@Column(name = "cd72")
	public Integer getCd72() {
		return this.cd72;
	}

	public void setCd72(Integer cd72) {
		this.cd72 = cd72;
	}

	@Column(name = "cd73")
	public Integer getCd73() {
		return this.cd73;
	}

	public void setCd73(Integer cd73) {
		this.cd73 = cd73;
	}

	@Column(name = "cd74")
	public Integer getCd74() {
		return this.cd74;
	}

	public void setCd74(Integer cd74) {
		this.cd74 = cd74;
	}

	@Column(name = "cd75")
	public Integer getCd75() {
		return this.cd75;
	}

	public void setCd75(Integer cd75) {
		this.cd75 = cd75;
	}

	@Column(name = "d7coment", length = 300)
	public String getD7coment() {
		return this.d7coment;
	}

	public void setD7coment(String d7coment) {
		this.d7coment = d7coment;
	}

	@Column(name = "cd81")
	public Integer getCd81() {
		return this.cd81;
	}

	public void setCd81(Integer cd81) {
		this.cd81 = cd81;
	}

	@Column(name = "cd82")
	public Integer getCd82() {
		return this.cd82;
	}

	public void setCd82(Integer cd82) {
		this.cd82 = cd82;
	}

	@Column(name = "cd83")
	public Integer getCd83() {
		return this.cd83;
	}

	public void setCd83(Integer cd83) {
		this.cd83 = cd83;
	}

	@Column(name = "cd84")
	public Integer getCd84() {
		return this.cd84;
	}

	public void setCd84(Integer cd84) {
		this.cd84 = cd84;
	}

	@Column(name = "cd85")
	public Integer getCd85() {
		return this.cd85;
	}

	public void setCd85(Integer cd85) {
		this.cd85 = cd85;
	}

	@Column(name = "d8coment", length = 300)
	public String getD8coment() {
		return this.d8coment;
	}

	public void setD8coment(String d8coment) {
		this.d8coment = d8coment;
	}

	@Column(name = "cd91")
	public Integer getCd91() {
		return this.cd91;
	}

	public void setCd91(Integer cd91) {
		this.cd91 = cd91;
	}

	@Column(name = "cd92")
	public Integer getCd92() {
		return this.cd92;
	}

	public void setCd92(Integer cd92) {
		this.cd92 = cd92;
	}

	@Column(name = "cd93")
	public Integer getCd93() {
		return this.cd93;
	}

	public void setCd93(Integer cd93) {
		this.cd93 = cd93;
	}

	@Column(name = "cd94")
	public Integer getCd94() {
		return this.cd94;
	}

	public void setCd94(Integer cd94) {
		this.cd94 = cd94;
	}

	@Column(name = "cd95")
	public Integer getCd95() {
		return this.cd95;
	}

	public void setCd95(Integer cd95) {
		this.cd95 = cd95;
	}

	@Column(name = "d9coment", length = 300)
	public String getD9coment() {
		return this.d9coment;
	}

	public void setD9coment(String d9coment) {
		this.d9coment = d9coment;
	}

	@Column(name = "cd101")
	public Integer getCd101() {
		return this.cd101;
	}

	public void setCd101(Integer cd101) {
		this.cd101 = cd101;
	}

	@Column(name = "cd102")
	public Integer getCd102() {
		return this.cd102;
	}

	public void setCd102(Integer cd102) {
		this.cd102 = cd102;
	}

	@Column(name = "cd103")
	public Integer getCd103() {
		return this.cd103;
	}

	public void setCd103(Integer cd103) {
		this.cd103 = cd103;
	}

	@Column(name = "cd104")
	public Integer getCd104() {
		return this.cd104;
	}

	public void setCd104(Integer cd104) {
		this.cd104 = cd104;
	}

	@Column(name = "cd105")
	public Integer getCd105() {
		return this.cd105;
	}

	public void setCd105(Integer cd105) {
		this.cd105 = cd105;
	}

	@Column(name = "d10coment", length = 300)
	public String getD10coment() {
		return this.d10coment;
	}

	public void setD10coment(String d10coment) {
		this.d10coment = d10coment;
	}

	@Column(name = "cd111")
	public Integer getCd111() {
		return this.cd111;
	}

	public void setCd111(Integer cd111) {
		this.cd111 = cd111;
	}

	@Column(name = "cd112")
	public Integer getCd112() {
		return this.cd112;
	}

	public void setCd112(Integer cd112) {
		this.cd112 = cd112;
	}

	@Column(name = "cd113")
	public Integer getCd113() {
		return this.cd113;
	}

	public void setCd113(Integer cd113) {
		this.cd113 = cd113;
	}

	@Column(name = "cd114")
	public Integer getCd114() {
		return this.cd114;
	}

	public void setCd114(Integer cd114) {
		this.cd114 = cd114;
	}

	@Column(name = "cd115")
	public Integer getCd115() {
		return this.cd115;
	}

	public void setCd115(Integer cd115) {
		this.cd115 = cd115;
	}

	@Column(name = "d11coment", length = 300)
	public String getD11coment() {
		return this.d11coment;
	}

	public void setD11coment(String d11coment) {
		this.d11coment = d11coment;
	}

	@Column(name = "cd121")
	public Integer getCd121() {
		return this.cd121;
	}

	public void setCd121(Integer cd121) {
		this.cd121 = cd121;
	}

	@Column(name = "cd122")
	public Integer getCd122() {
		return this.cd122;
	}

	public void setCd122(Integer cd122) {
		this.cd122 = cd122;
	}

	@Column(name = "cd123")
	public Integer getCd123() {
		return this.cd123;
	}

	public void setCd123(Integer cd123) {
		this.cd123 = cd123;
	}

	@Column(name = "cd124")
	public Integer getCd124() {
		return this.cd124;
	}

	public void setCd124(Integer cd124) {
		this.cd124 = cd124;
	}

	@Column(name = "cd125")
	public Integer getCd125() {
		return this.cd125;
	}

	public void setCd125(Integer cd125) {
		this.cd125 = cd125;
	}

	@Column(name = "d12coment", length = 300)
	public String getD12coment() {
		return this.d12coment;
	}

	public void setD12coment(String d12coment) {
		this.d12coment = d12coment;
	}

	@Column(name = "cd131")
	public Integer getCd131() {
		return this.cd131;
	}

	public void setCd131(Integer cd131) {
		this.cd131 = cd131;
	}

	@Column(name = "cd132")
	public Integer getCd132() {
		return this.cd132;
	}

	public void setCd132(Integer cd132) {
		this.cd132 = cd132;
	}

	@Column(name = "cd133")
	public Integer getCd133() {
		return this.cd133;
	}

	public void setCd133(Integer cd133) {
		this.cd133 = cd133;
	}

	@Column(name = "cd134")
	public Integer getCd134() {
		return this.cd134;
	}

	public void setCd134(Integer cd134) {
		this.cd134 = cd134;
	}

	@Column(name = "cd135")
	public Integer getCd135() {
		return this.cd135;
	}

	public void setCd135(Integer cd135) {
		this.cd135 = cd135;
	}

	@Column(name = "d13coment", length = 300)
	public String getD13coment() {
		return this.d13coment;
	}

	public void setD13coment(String d13coment) {
		this.d13coment = d13coment;
	}

	@Column(name = "cd141")
	public Integer getCd141() {
		return this.cd141;
	}

	public void setCd141(Integer cd141) {
		this.cd141 = cd141;
	}

	@Column(name = "cd142")
	public Integer getCd142() {
		return this.cd142;
	}

	public void setCd142(Integer cd142) {
		this.cd142 = cd142;
	}

	@Column(name = "cd143")
	public Integer getCd143() {
		return this.cd143;
	}

	public void setCd143(Integer cd143) {
		this.cd143 = cd143;
	}

	@Column(name = "cd144")
	public Integer getCd144() {
		return this.cd144;
	}

	public void setCd144(Integer cd144) {
		this.cd144 = cd144;
	}

	@Column(name = "cd145")
	public Integer getCd145() {
		return this.cd145;
	}

	public void setCd145(Integer cd145) {
		this.cd145 = cd145;
	}

	@Column(name = "d14coment", length = 300)
	public String getD14coment() {
		return this.d14coment;
	}

	public void setD14coment(String d14coment) {
		this.d14coment = d14coment;
	}

	@Column(name = "cd151")
	public Integer getCd151() {
		return this.cd151;
	}

	public void setCd151(Integer cd151) {
		this.cd151 = cd151;
	}

	@Column(name = "cd152")
	public Integer getCd152() {
		return this.cd152;
	}

	public void setCd152(Integer cd152) {
		this.cd152 = cd152;
	}

	@Column(name = "cd153")
	public Integer getCd153() {
		return this.cd153;
	}

	public void setCd153(Integer cd153) {
		this.cd153 = cd153;
	}

	@Column(name = "cd154")
	public Integer getCd154() {
		return this.cd154;
	}

	public void setCd154(Integer cd154) {
		this.cd154 = cd154;
	}

	@Column(name = "cd155")
	public Integer getCd155() {
		return this.cd155;
	}

	public void setCd155(Integer cd155) {
		this.cd155 = cd155;
	}

	@Column(name = "d15coment", length = 300)
	public String getD15coment() {
		return this.d15coment;
	}

	public void setD15coment(String d15coment) {
		this.d15coment = d15coment;
	}

	@Column(name = "cd161")
	public Integer getCd161() {
		return this.cd161;
	}

	public void setCd161(Integer cd161) {
		this.cd161 = cd161;
	}

	@Column(name = "cd162")
	public Integer getCd162() {
		return this.cd162;
	}

	public void setCd162(Integer cd162) {
		this.cd162 = cd162;
	}

	@Column(name = "cd163")
	public Integer getCd163() {
		return this.cd163;
	}

	public void setCd163(Integer cd163) {
		this.cd163 = cd163;
	}

	@Column(name = "cd164")
	public Integer getCd164() {
		return this.cd164;
	}

	public void setCd164(Integer cd164) {
		this.cd164 = cd164;
	}

	@Column(name = "cd165")
	public Integer getCd165() {
		return this.cd165;
	}

	public void setCd165(Integer cd165) {
		this.cd165 = cd165;
	}

	@Column(name = "d16coment", length = 300)
	public String getD16coment() {
		return this.d16coment;
	}

	public void setD16coment(String d16coment) {
		this.d16coment = d16coment;
	}

	@Column(name = "cd171")
	public Integer getCd171() {
		return this.cd171;
	}

	public void setCd171(Integer cd171) {
		this.cd171 = cd171;
	}

	@Column(name = "cd172")
	public Integer getCd172() {
		return this.cd172;
	}

	public void setCd172(Integer cd172) {
		this.cd172 = cd172;
	}

	@Column(name = "cd173")
	public Integer getCd173() {
		return this.cd173;
	}

	public void setCd173(Integer cd173) {
		this.cd173 = cd173;
	}

	@Column(name = "cd174")
	public Integer getCd174() {
		return this.cd174;
	}

	public void setCd174(Integer cd174) {
		this.cd174 = cd174;
	}

	@Column(name = "cd175")
	public Integer getCd175() {
		return this.cd175;
	}

	public void setCd175(Integer cd175) {
		this.cd175 = cd175;
	}

	@Column(name = "d17coment", length = 300)
	public String getD17coment() {
		return this.d17coment;
	}

	public void setD17coment(String d17coment) {
		this.d17coment = d17coment;
	}

	@Column(name = "cd181")
	public Integer getCd181() {
		return this.cd181;
	}

	public void setCd181(Integer cd181) {
		this.cd181 = cd181;
	}

	@Column(name = "cd182")
	public Integer getCd182() {
		return this.cd182;
	}

	public void setCd182(Integer cd182) {
		this.cd182 = cd182;
	}

	@Column(name = "cd183")
	public Integer getCd183() {
		return this.cd183;
	}

	public void setCd183(Integer cd183) {
		this.cd183 = cd183;
	}

	@Column(name = "cd184")
	public Integer getCd184() {
		return this.cd184;
	}

	public void setCd184(Integer cd184) {
		this.cd184 = cd184;
	}

	@Column(name = "cd185")
	public Integer getCd185() {
		return this.cd185;
	}

	public void setCd185(Integer cd185) {
		this.cd185 = cd185;
	}

	@Column(name = "d18coment", length = 300)
	public String getD18coment() {
		return this.d18coment;
	}

	public void setD18coment(String d18coment) {
		this.d18coment = d18coment;
	}

	@Column(name = "cd191")
	public Integer getCd191() {
		return this.cd191;
	}

	public void setCd191(Integer cd191) {
		this.cd191 = cd191;
	}

	@Column(name = "cd192")
	public Integer getCd192() {
		return this.cd192;
	}

	public void setCd192(Integer cd192) {
		this.cd192 = cd192;
	}

	@Column(name = "cd193")
	public Integer getCd193() {
		return this.cd193;
	}

	public void setCd193(Integer cd193) {
		this.cd193 = cd193;
	}

	@Column(name = "cd194")
	public Integer getCd194() {
		return this.cd194;
	}

	public void setCd194(Integer cd194) {
		this.cd194 = cd194;
	}

	@Column(name = "cd195")
	public Integer getCd195() {
		return this.cd195;
	}

	public void setCd195(Integer cd195) {
		this.cd195 = cd195;
	}

	@Column(name = "d19coment", length = 300)
	public String getD19coment() {
		return this.d19coment;
	}

	public void setD19coment(String d19coment) {
		this.d19coment = d19coment;
	}

	@Column(name = "cd201")
	public Integer getCd201() {
		return this.cd201;
	}

	public void setCd201(Integer cd201) {
		this.cd201 = cd201;
	}

	@Column(name = "cd202")
	public Integer getCd202() {
		return this.cd202;
	}

	public void setCd202(Integer cd202) {
		this.cd202 = cd202;
	}

	@Column(name = "cd203")
	public Integer getCd203() {
		return this.cd203;
	}

	public void setCd203(Integer cd203) {
		this.cd203 = cd203;
	}

	@Column(name = "cd204")
	public Integer getCd204() {
		return this.cd204;
	}

	public void setCd204(Integer cd204) {
		this.cd204 = cd204;
	}

	@Column(name = "cd205")
	public Integer getCd205() {
		return this.cd205;
	}

	public void setCd205(Integer cd205) {
		this.cd205 = cd205;
	}

	@Column(name = "d20coment", length = 300)
	public String getD20coment() {
		return this.d20coment;
	}

	public void setD20coment(String d20coment) {
		this.d20coment = d20coment;
	}

	@Column(name = "cd211")
	public Integer getCd211() {
		return this.cd211;
	}

	public void setCd211(Integer cd211) {
		this.cd211 = cd211;
	}

	@Column(name = "cd212")
	public Integer getCd212() {
		return this.cd212;
	}

	public void setCd212(Integer cd212) {
		this.cd212 = cd212;
	}

	@Column(name = "cd213")
	public Integer getCd213() {
		return this.cd213;
	}

	public void setCd213(Integer cd213) {
		this.cd213 = cd213;
	}

	@Column(name = "cd214")
	public Integer getCd214() {
		return this.cd214;
	}

	public void setCd214(Integer cd214) {
		this.cd214 = cd214;
	}

	@Column(name = "cd215")
	public Integer getCd215() {
		return this.cd215;
	}

	public void setCd215(Integer cd215) {
		this.cd215 = cd215;
	}

	@Column(name = "d21coment", length = 300)
	public String getD21coment() {
		return this.d21coment;
	}

	public void setD21coment(String d21coment) {
		this.d21coment = d21coment;
	}

	@Column(name = "cd221")
	public Integer getCd221() {
		return this.cd221;
	}

	public void setCd221(Integer cd221) {
		this.cd221 = cd221;
	}

	@Column(name = "cd222")
	public Integer getCd222() {
		return this.cd222;
	}

	public void setCd222(Integer cd222) {
		this.cd222 = cd222;
	}

	@Column(name = "cd223")
	public Integer getCd223() {
		return this.cd223;
	}

	public void setCd223(Integer cd223) {
		this.cd223 = cd223;
	}

	@Column(name = "cd224")
	public Integer getCd224() {
		return this.cd224;
	}

	public void setCd224(Integer cd224) {
		this.cd224 = cd224;
	}

	@Column(name = "cd225")
	public Integer getCd225() {
		return this.cd225;
	}

	public void setCd225(Integer cd225) {
		this.cd225 = cd225;
	}

	@Column(name = "d22coment", length = 300)
	public String getD22coment() {
		return this.d22coment;
	}

	public void setD22coment(String d22coment) {
		this.d22coment = d22coment;
	}

	@Column(name = "cd231")
	public Integer getCd231() {
		return this.cd231;
	}

	public void setCd231(Integer cd231) {
		this.cd231 = cd231;
	}

	@Column(name = "cd232")
	public Integer getCd232() {
		return this.cd232;
	}

	public void setCd232(Integer cd232) {
		this.cd232 = cd232;
	}

	@Column(name = "cd233")
	public Integer getCd233() {
		return this.cd233;
	}

	public void setCd233(Integer cd233) {
		this.cd233 = cd233;
	}

	@Column(name = "cd234")
	public Integer getCd234() {
		return this.cd234;
	}

	public void setCd234(Integer cd234) {
		this.cd234 = cd234;
	}

	@Column(name = "cd235")
	public Integer getCd235() {
		return this.cd235;
	}

	public void setCd235(Integer cd235) {
		this.cd235 = cd235;
	}

	@Column(name = "d23coment", length = 300)
	public String getD23coment() {
		return this.d23coment;
	}

	public void setD23coment(String d23coment) {
		this.d23coment = d23coment;
	}

	@Column(name = "cd241")
	public Integer getCd241() {
		return this.cd241;
	}

	public void setCd241(Integer cd241) {
		this.cd241 = cd241;
	}

	@Column(name = "cd242")
	public Integer getCd242() {
		return this.cd242;
	}

	public void setCd242(Integer cd242) {
		this.cd242 = cd242;
	}

	@Column(name = "cd243")
	public Integer getCd243() {
		return this.cd243;
	}

	public void setCd243(Integer cd243) {
		this.cd243 = cd243;
	}

	@Column(name = "cd244")
	public Integer getCd244() {
		return this.cd244;
	}

	public void setCd244(Integer cd244) {
		this.cd244 = cd244;
	}

	@Column(name = "cd245")
	public Integer getCd245() {
		return this.cd245;
	}

	public void setCd245(Integer cd245) {
		this.cd245 = cd245;
	}

	@Column(name = "d24coment", length = 300)
	public String getD24coment() {
		return this.d24coment;
	}

	public void setD24coment(String d24coment) {
		this.d24coment = d24coment;
	}

	@Column(name = "cd251")
	public Integer getCd251() {
		return this.cd251;
	}

	public void setCd251(Integer cd251) {
		this.cd251 = cd251;
	}

	@Column(name = "cd252")
	public Integer getCd252() {
		return this.cd252;
	}

	public void setCd252(Integer cd252) {
		this.cd252 = cd252;
	}

	@Column(name = "cd253")
	public Integer getCd253() {
		return this.cd253;
	}

	public void setCd253(Integer cd253) {
		this.cd253 = cd253;
	}

	@Column(name = "cd254")
	public Integer getCd254() {
		return this.cd254;
	}

	public void setCd254(Integer cd254) {
		this.cd254 = cd254;
	}

	@Column(name = "cd255")
	public Integer getCd255() {
		return this.cd255;
	}

	public void setCd255(Integer cd255) {
		this.cd255 = cd255;
	}

	@Column(name = "d25coment", length = 300)
	public String getD25coment() {
		return this.d25coment;
	}

	public void setD25coment(String d25coment) {
		this.d25coment = d25coment;
	}

	@Column(name = "cd261")
	public Integer getCd261() {
		return this.cd261;
	}

	public void setCd261(Integer cd261) {
		this.cd261 = cd261;
	}

	@Column(name = "cd262")
	public Integer getCd262() {
		return this.cd262;
	}

	public void setCd262(Integer cd262) {
		this.cd262 = cd262;
	}

	@Column(name = "cd263")
	public Integer getCd263() {
		return this.cd263;
	}

	public void setCd263(Integer cd263) {
		this.cd263 = cd263;
	}

	@Column(name = "cd264")
	public Integer getCd264() {
		return this.cd264;
	}

	public void setCd264(Integer cd264) {
		this.cd264 = cd264;
	}

	@Column(name = "cd265")
	public Integer getCd265() {
		return this.cd265;
	}

	public void setCd265(Integer cd265) {
		this.cd265 = cd265;
	}

	@Column(name = "d26coment", length = 300)
	public String getD26coment() {
		return this.d26coment;
	}

	public void setD26coment(String d26coment) {
		this.d26coment = d26coment;
	}

	@Column(name = "cd271")
	public Integer getCd271() {
		return this.cd271;
	}

	public void setCd271(Integer cd271) {
		this.cd271 = cd271;
	}

	@Column(name = "cd272")
	public Integer getCd272() {
		return this.cd272;
	}

	public void setCd272(Integer cd272) {
		this.cd272 = cd272;
	}

	@Column(name = "cd273")
	public Integer getCd273() {
		return this.cd273;
	}

	public void setCd273(Integer cd273) {
		this.cd273 = cd273;
	}

	@Column(name = "cd274")
	public Integer getCd274() {
		return this.cd274;
	}

	public void setCd274(Integer cd274) {
		this.cd274 = cd274;
	}

	@Column(name = "cd275")
	public Integer getCd275() {
		return this.cd275;
	}

	public void setCd275(Integer cd275) {
		this.cd275 = cd275;
	}

	@Column(name = "d27coment", length = 300)
	public String getD27coment() {
		return this.d27coment;
	}

	public void setD27coment(String d27coment) {
		this.d27coment = d27coment;
	}

	@Column(name = "cd281")
	public Integer getCd281() {
		return this.cd281;
	}

	public void setCd281(Integer cd281) {
		this.cd281 = cd281;
	}

	@Column(name = "cd282")
	public Integer getCd282() {
		return this.cd282;
	}

	public void setCd282(Integer cd282) {
		this.cd282 = cd282;
	}

	@Column(name = "cd283")
	public Integer getCd283() {
		return this.cd283;
	}

	public void setCd283(Integer cd283) {
		this.cd283 = cd283;
	}

	@Column(name = "cd284")
	public Integer getCd284() {
		return this.cd284;
	}

	public void setCd284(Integer cd284) {
		this.cd284 = cd284;
	}

	@Column(name = "cd285")
	public Integer getCd285() {
		return this.cd285;
	}

	public void setCd285(Integer cd285) {
		this.cd285 = cd285;
	}

	@Column(name = "d28coment", length = 300)
	public String getD28coment() {
		return this.d28coment;
	}

	public void setD28coment(String d28coment) {
		this.d28coment = d28coment;
	}

	@Column(name = "cd291")
	public Integer getCd291() {
		return this.cd291;
	}

	public void setCd291(Integer cd291) {
		this.cd291 = cd291;
	}

	@Column(name = "cd292")
	public Integer getCd292() {
		return this.cd292;
	}

	public void setCd292(Integer cd292) {
		this.cd292 = cd292;
	}

	@Column(name = "cd293")
	public Integer getCd293() {
		return this.cd293;
	}

	public void setCd293(Integer cd293) {
		this.cd293 = cd293;
	}

	@Column(name = "cd294")
	public Integer getCd294() {
		return this.cd294;
	}

	public void setCd294(Integer cd294) {
		this.cd294 = cd294;
	}

	@Column(name = "cd295")
	public Integer getCd295() {
		return this.cd295;
	}

	public void setCd295(Integer cd295) {
		this.cd295 = cd295;
	}

	@Column(name = "d29coment", length = 300)
	public String getD29coment() {
		return this.d29coment;
	}

	public void setD29coment(String d29coment) {
		this.d29coment = d29coment;
	}

	@Column(name = "cd301")
	public Integer getCd301() {
		return this.cd301;
	}

	public void setCd301(Integer cd301) {
		this.cd301 = cd301;
	}

	@Column(name = "cd302")
	public Integer getCd302() {
		return this.cd302;
	}

	public void setCd302(Integer cd302) {
		this.cd302 = cd302;
	}

	@Column(name = "cd303")
	public Integer getCd303() {
		return this.cd303;
	}

	public void setCd303(Integer cd303) {
		this.cd303 = cd303;
	}

	@Column(name = "cd304")
	public Integer getCd304() {
		return this.cd304;
	}

	public void setCd304(Integer cd304) {
		this.cd304 = cd304;
	}

	@Column(name = "cd305")
	public Integer getCd305() {
		return this.cd305;
	}

	public void setCd305(Integer cd305) {
		this.cd305 = cd305;
	}

	@Column(name = "d30coment", length = 300)
	public String getD30coment() {
		return this.d30coment;
	}

	public void setD30coment(String d30coment) {
		this.d30coment = d30coment;
	}

	@Column(name = "cd311")
	public Integer getCd311() {
		return this.cd311;
	}

	public void setCd311(Integer cd311) {
		this.cd311 = cd311;
	}

	@Column(name = "cd312")
	public Integer getCd312() {
		return this.cd312;
	}

	public void setCd312(Integer cd312) {
		this.cd312 = cd312;
	}

	@Column(name = "cd313")
	public Integer getCd313() {
		return this.cd313;
	}

	public void setCd313(Integer cd313) {
		this.cd313 = cd313;
	}

	@Column(name = "cd314")
	public Integer getCd314() {
		return this.cd314;
	}

	public void setCd314(Integer cd314) {
		this.cd314 = cd314;
	}

	@Column(name = "cd315")
	public Integer getCd315() {
		return this.cd315;
	}

	public void setCd315(Integer cd315) {
		this.cd315 = cd315;
	}

	@Column(name = "d31coment", length = 300)
	public String getD31coment() {
		return this.d31coment;
	}

	public void setD31coment(String d31coment) {
		this.d31coment = d31coment;
	}

	@Column(name = "cd321")
	public Integer getCd321() {
		return this.cd321;
	}

	public void setCd321(Integer cd321) {
		this.cd321 = cd321;
	}

	@Column(name = "cd322")
	public Integer getCd322() {
		return this.cd322;
	}

	public void setCd322(Integer cd322) {
		this.cd322 = cd322;
	}

	@Column(name = "cd323")
	public Integer getCd323() {
		return this.cd323;
	}

	public void setCd323(Integer cd323) {
		this.cd323 = cd323;
	}

	@Column(name = "cd324")
	public Integer getCd324() {
		return this.cd324;
	}

	public void setCd324(Integer cd324) {
		this.cd324 = cd324;
	}

	@Column(name = "cd325")
	public Integer getCd325() {
		return this.cd325;
	}

	public void setCd325(Integer cd325) {
		this.cd325 = cd325;
	}

	@Column(name = "d32coment", length = 300)
	public String getD32coment() {
		return this.d32coment;
	}

	public void setD32coment(String d32coment) {
		this.d32coment = d32coment;
	}

}
