package com.unbosque.entidad;
// default package
// Generated Apr 26, 2015 6:24:07 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "public")
public class Usuario implements java.io.Serializable {

	private int id;
	private String login;
	private String password;
	private String apellidosNombres;
	private Date fechaCreacion;
	private char estado;
	private String correo;
	private Date fechaClave;
	private Character tipoUsuario;
	private Integer idProyecto;
	private String proyecto;


	public Usuario() {
	}

	public Usuario(int id, String login, String password,
			String apellidosNombres, char estado) {
		this.id = id;
		this.login = login;
		this.password = password;
		this.apellidosNombres = apellidosNombres;
		this.estado = estado;
	}

	public Usuario(int id, String login, String password,
			String apellidosNombres, Date fechaCreacion, char estado,
			String correo, Date fechaClave, Character tipoUsuario,
			Integer idProyecto) {
		this.id = id;
		this.login = login;
		this.password = password;
		this.apellidosNombres = apellidosNombres;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.correo = correo;
		this.fechaClave = fechaClave;
		this.tipoUsuario = tipoUsuario;
		this.idProyecto = idProyecto;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "login", nullable = false, length = 8)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false, length = 256)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "apellidos_nombres", nullable = false, length = 60)
	public String getApellidosNombres() {
		return this.apellidosNombres;
	}

	public void setApellidosNombres(String apellidosNombres) {
		this.apellidosNombres = apellidosNombres;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 35)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "correo", length = 60)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_clave", length = 35)
	public Date getFechaClave() {
		return this.fechaClave;
	}

	public void setFechaClave(Date fechaClave) {
		this.fechaClave = fechaClave;
	}

	@Column(name = "tipo_usuario", length = 1)
	public Character getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(Character tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@Column(name = "id_proyecto")
	public Integer getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(Integer idProyecto) {
		this.idProyecto = idProyecto;
	}
	
	@Column(name = "proyecto")
	public String getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(String proyecto) {
		this.proyecto = proyecto;
	}

}
